export const THAI_STOCKS = [
  { symbol: "AAV.BK", name: "Asia Aviation (เอเชีย เอวิเอชั่น / AAV)", type: "EQUITY", exchange: "SET" },
  { symbol: "ADVANC.BK", name: "Advanced Info Service (แอดวานซ์ อินโฟร์ เซอร์วิส / AIS / ADVANC)", type: "EQUITY", exchange: "SET" },
  { symbol: "AEONTS.BK", name: "Aeon Thana Sinsap (อิออน ธนสินทรัพย์ / AEONTS)", type: "EQUITY", exchange: "SET" },
  { symbol: "AMATA.BK", name: "Amata Corporation (อมตะ คอร์ปอเรชัน / AMATA)", type: "EQUITY", exchange: "SET" },
  { symbol: "AOT.BK", name: "Airports of Thailand (ท่าอากาศยานไทย / AOT)", type: "EQUITY", exchange: "SET" },
  { symbol: "AP.BK", name: "AP Thailand (เอพี ไทยแลนด์ / AP)", type: "EQUITY", exchange: "SET" },
  { symbol: "AWC.BK", name: "Asset World Corp (แอสเสท เวิรลด์ คอร์ป / AWC)", type: "EQUITY", exchange: "SET" },
  { symbol: "BAM.BK", name: "Bangkok Commercial Asset Management (กรุงเทพพาณิชย์ / BAM)", type: "EQUITY", exchange: "SET" },
  { symbol: "BANPU.BK", name: "Banpu (บ้านปู / BANPU)", type: "EQUITY", exchange: "SET" },
  { symbol: "BBL.BK", name: "Bangkok Bank (ธนาคารกรุงเทพ / BBL)", type: "EQUITY", exchange: "SET" },
  { symbol: "BCH.BK", name: "Bangkok Chain Hospital (บางกอก เชน ฮอสปิทอล / BCH)", type: "EQUITY", exchange: "SET" },
  { symbol: "BCP.BK", name: "Bangchak Corporation (บางจาก คอร์ปอเรชัน / BCP)", type: "EQUITY", exchange: "SET" },
  { symbol: "BCPG.BK", name: "BCPG (บีซีพีจี / BCPG)", type: "EQUITY", exchange: "SET" },
  { symbol: "BDMS.BK", name: "Bangkok Dusit Medical Services (กรุงเทพดุสิตเวชการ / BDMS)", type: "EQUITY", exchange: "SET" },
  { symbol: "BEM.BK", name: "Bangkok Expressway and Metro (ทางด่วนและรถไฟฟ้ากรุงเทพ / BEM)", type: "EQUITY", exchange: "SET" },
  { symbol: "BGRIM.BK", name: "B.Grimm Power (บี.กริม เพาเวอร์ / BGRIM)", type: "EQUITY", exchange: "SET" },
  { symbol: "BH.BK", name: "Bumrungrad Hospital (โรงพยาบาลบำรุงราษฎร์ / BH)", type: "EQUITY", exchange: "SET" },
  { symbol: "BJC.BK", name: "Berli Jucker (เบอร์ลี่ ยุคเกอร์ / BJC)", type: "EQUITY", exchange: "SET" },
  { symbol: "BTS.BK", name: "BTS Group Holdings (บีทีเอส กรุ๊ป โฮลดิ้งส์ / BTS)", type: "EQUITY", exchange: "SET" },
  { symbol: "BYD.BK", name: "Beyond Securities (บียอนด์ / BYD)", type: "EQUITY", exchange: "SET" },
  { symbol: "CBG.BK", name: "Carabao Group (คาราบาวกรุ๊ป / CBG)", type: "EQUITY", exchange: "SET" },
  { symbol: "CENTEL.BK", name: "Central Plaza Hotel (โรงแรมเซ็นทรัลพลาซา / CENTEL)", type: "EQUITY", exchange: "SET" },
  { symbol: "CHG.BK", name: "Chularat Hospital (โรงพยาบาลจุฬารัตน์ / CHG)", type: "EQUITY", exchange: "SET" },
  { symbol: "CK.BK", name: "CH. Karnchang (ช.การช่าง / CK)", type: "EQUITY", exchange: "SET" },
  { symbol: "CKP.BK", name: "CK Power (ซีเค พาวเวอร์ / CKP)", type: "EQUITY", exchange: "SET" },
  { symbol: "COM7.BK", name: "Com7 (คอมเซเว่น / COM7)", type: "EQUITY", exchange: "SET" },
  { symbol: "CPALL.BK", name: "CP ALL (ซีพี ออลล์ / CPALL)", type: "EQUITY", exchange: "SET" },
  { symbol: "CPF.BK", name: "Charoen Pokphand Foods (เจริญโภคภัณฑ์อาหาร / CPF)", type: "EQUITY", exchange: "SET" },
  { symbol: "CPN.BK", name: "Central Pattana (เซ็นทรัลพัฒนา / CPN)", type: "EQUITY", exchange: "SET" },
  { symbol: "CRC.BK", name: "Central Retail Corporation (เซ็นทรัล รีเทล คอร์ปอเรชัน / CRC)", type: "EQUITY", exchange: "SET" },
  { symbol: "DELTA.BK", name: "Delta Electronics (เดลต้า อีเลคโทรนิคส์ / DELTA)", type: "EQUITY", exchange: "SET" },
  { symbol: "DOHOME.BK", name: "Dohome (ดูโฮม / DOHOME)", type: "EQUITY", exchange: "SET" },
  { symbol: "EA.BK", name: "Energy Absolute (พลังงานบริสุทธิ์ / EA)", type: "EQUITY", exchange: "SET" },
  { symbol: "EASTW.BK", name: "Eastern Water Resources (จัดการและพัฒนาทรัพยากรน้ำภาคตะวันออก / EASTW)", type: "EQUITY", exchange: "SET" },
  { symbol: "EGCO.BK", name: "Electricity Generating (ผลิตไฟฟ้า / EGCO)", type: "EQUITY", exchange: "SET" },
  { symbol: "EPG.BK", name: "Eastern Polymer Group (อีสเทิร์น โพลีเมอร์ กรุ๊ป / EPG)", type: "EQUITY", exchange: "SET" },
  { symbol: "ERW.BK", name: "The Erawan Group (ดิ เอราวัณ กรุ๊ป / ERW)", type: "EQUITY", exchange: "SET" },
  { symbol: "GFPT.BK", name: "GFPT (จีเอฟพีที / GFPT)", type: "EQUITY", exchange: "SET" },
  { symbol: "GLOBAL.BK", name: "Siam Global House (สยามโกลบอลเฮ้าส์ / GLOBAL)", type: "EQUITY", exchange: "SET" },
  { symbol: "GPSC.BK", name: "Global Power Synergy (โกลบอล เพาเวอร์ ซินเนอร์ยี่ / GPSC)", type: "EQUITY", exchange: "SET" },
  { symbol: "GULF.BK", name: "Gulf Energy Development (กัลฟ์ เอ็นเนอร์จี ดีเวลลอปเมนท์ / GULF)", type: "EQUITY", exchange: "SET" },
  { symbol: "GUNKUL.BK", name: "Gunkul Engineering (กันกุลเอ็นจิเนียริ่ง / GUNKUL)", type: "EQUITY", exchange: "SET" },
  { symbol: "HANA.BK", name: "Hana Microelectronics (ฮานา ไมโครอิเล็คโทรนิคส / HANA)", type: "EQUITY", exchange: "SET" },
  { symbol: "HMPRO.BK", name: "Home Product Center (โฮม โปรดักส์ เซ็นเตอร์ / HMPRO)", type: "EQUITY", exchange: "SET" },
  { symbol: "ICHITAN.BK", name: "Ichitan Group (อิชิตัน กรุ๊ป / ICHI / ICHITAN)", type: "EQUITY", exchange: "SET" },
  { symbol: "ICHI.BK", name: "Ichitan Group (อิชิตัน กรุ๊ป / ICHI / ICHITAN)", type: "EQUITY", exchange: "SET" },
  { symbol: "INTUCH.BK", name: "Intouch Holdings (อินทัช โฮลดิ้งส์ / INTUCH)", type: "EQUITY", exchange: "SET" },
  { symbol: "IRPC.BK", name: "IRPC (ไออาร์พีซี / IRPC)", type: "EQUITY", exchange: "SET" },
  { symbol: "ITD.BK", name: "Italian-Thai Development (อิตาเลียนไทย ดีเวล๊อปเมนต์ / ITD)", type: "EQUITY", exchange: "SET" },
  { symbol: "IVL.BK", name: "Indorama Ventures (อินโดรามา เวนเจอร์ส / IVL)", type: "EQUITY", exchange: "SET" },
  { symbol: "JAS.BK", name: "Jasmine International (จัสมิน อินเตอร์เนชั่นแนล / JAS)", type: "EQUITY", exchange: "SET" },
  { symbol: "JMART.BK", name: "Jaymart Group (เจมาร์ท กรุ๊ป / JMART)", type: "EQUITY", exchange: "SET" },
  { symbol: "JMT.BK", name: "JMT Network Services (เจ เอ็ม ที เน็ทเวอร์ค เซอร์วิสเซ็ส / JMT)", type: "EQUITY", exchange: "SET" },
  { symbol: "KBANK.BK", name: "Kasikornbank (ธนาคารกสิกรไทย / KBANK)", type: "EQUITY", exchange: "SET" },
  { symbol: "KCE.BK", name: "KCE Electronics (เคซีอี อีเลคโทรนิคส์ / KCE)", type: "EQUITY", exchange: "SET" },
  { symbol: "KEX.BK", name: "Kerry Express (เคอรี่ เอ็กซ์เพรส / KEX / KERRY)", type: "EQUITY", exchange: "SET" },
  { symbol: "KERRY.BK", name: "Kerry Express (เคอรี่ เอ็กซ์เพรส / KEX / KERRY)", type: "EQUITY", exchange: "SET" },
  { symbol: "KKP.BK", name: "Kiatnakin Phatra Bank (ธนาคารเกียรตินาคินภัทร / KKP)", type: "EQUITY", exchange: "SET" },
  { symbol: "KTB.BK", name: "Krung Thai Bank (ธนาคารกรุงไทย / KTB)", type: "EQUITY", exchange: "SET" },
  { symbol: "KTC.BK", name: "Krungthai Card (บัตรกรุงไทย / KTC)", type: "EQUITY", exchange: "SET" },
  { symbol: "LH.BK", name: "Land and Houses (แลนด์แอนด์เฮ้าส์ / LH)", type: "EQUITY", exchange: "SET" },
  { symbol: "LPN.BK", name: "L.P.N. Development (แอล.พี.เอ็น. ดีเวลลอปเมนท์ / LPN)", type: "EQUITY", exchange: "SET" },
  { symbol: "M.BK", name: "MK Restaurants (เอ็มเค เรสโตรองต์ กรุ๊ป / MK / M)", type: "EQUITY", exchange: "SET" },
  { symbol: "MAJOR.BK", name: "Major Cineplex Group (เมเจอร์ ซีนีเพล็กซ์ กรุ๊ป / MAJOR)", type: "EQUITY", exchange: "SET" },
  { symbol: "MBK.BK", name: "MBK (เอ็ม บี เค / MBK)", type: "EQUITY", exchange: "SET" },
  { symbol: "MEGA.BK", name: "Mega Lifesciences (เมก้า ไลฟ์ไซแอ็นเซส / MEGA)", type: "EQUITY", exchange: "SET" },
  { symbol: "MINT.BK", name: "Minor International (ไมเนอร์ อินเตอร์เนชั่นแนล / MINT)", type: "EQUITY", exchange: "SET" },
  { symbol: "MTC.BK", name: "Muangthai Capital (เมืองไทย แคปปิตอล / MTC)", type: "EQUITY", exchange: "SET" },
  { symbol: "NER.BK", name: "North East Rubber (นอร์ทอีส รับเบอร์ / NER)", type: "EQUITY", exchange: "SET" },
  { symbol: "NOBLE.BK", name: "Noble Development (โนเบิล ดีเวลลอปเมนท์ / NOBLE)", type: "EQUITY", exchange: "SET" },
  { symbol: "NUSA.BK", name: "Nusasiri (ณุศาศิริ / NUSA)", type: "EQUITY", exchange: "SET" },
  { symbol: "ORI.BK", name: "Origin Property (ออริจิ้น พร็อพเพอร์ตี้ / ORI)", type: "EQUITY", exchange: "SET" },
  { symbol: "OSP.BK", name: "Osotspa (โอสถสภา / OSP)", type: "EQUITY", exchange: "SET" },
  { symbol: "PLANB.BK", name: "Plan B Media (แพลน บี มีเดีย / PLANB)", type: "EQUITY", exchange: "SET" },
  { symbol: "PRM.BK", name: "Prima Marine (พริมา มารีน / PRM)", type: "EQUITY", exchange: "SET" },
  { symbol: "PSH.BK", name: "Pruksa Holding (พฤกษา โฮลดิ้ง / PSH)", type: "EQUITY", exchange: "SET" },
  { symbol: "PTG.BK", name: "PTG Energy (พีทีจี เอ็นเนอยี / PTG)", type: "EQUITY", exchange: "SET" },
  { symbol: "PTT.BK", name: "PTT Public Company (ปตท. / PTT)", type: "EQUITY", exchange: "SET" },
  { symbol: "PTTEP.BK", name: "PTT Exploration and Production (ปตท.สผ. / PTTEP)", type: "EQUITY", exchange: "SET" },
  { symbol: "PTTGC.BK", name: "PTT Global Chemical (พีทีที โกลบอล เคมิคอล / PTTGC)", type: "EQUITY", exchange: "SET" },
  { symbol: "QH.BK", name: "Quality Houses (ควอลิตี้ เฮ้าส์ / QH)", type: "EQUITY", exchange: "SET" },
  { symbol: "RATCH.BK", name: "Ratch Group (ราช กรุ๊ป / RATCH)", type: "EQUITY", exchange: "SET" },
  { symbol: "RBF.BK", name: "R&B Food Supply (อาร์แอนด์บี ฟู้ด ซัพพลาย / RBF)", type: "EQUITY", exchange: "SET" },
  { symbol: "RS.BK", name: "RS Public Company (อาร์เอส / RS)", type: "EQUITY", exchange: "SET" },
  { symbol: "SABUY.BK", name: "Sabuy Technology (สบาย เทคโนโลยี / SABUY)", type: "EQUITY", exchange: "SET" },
  { symbol: "SAMART.BK", name: "Samart Corporation (สามารถคอร์ปอเรชัน / SAMART)", type: "EQUITY", exchange: "SET" },
  { symbol: "SAPPE.BK", name: "Sappe (เซ็ปเป้ / SAPPE)", type: "EQUITY", exchange: "SET" },
  { symbol: "SAWAD.BK", name: "Srisawad Corporation (ศรีสวัสดิ์ คอร์ปอเรชัน / SAWAD)", type: "EQUITY", exchange: "SET" },
  { symbol: "SC.BK", name: "SC Asset Corporation (เอสซี แอสเสท คอร์ปอเรชัน / SC)", type: "EQUITY", exchange: "SET" },
  { symbol: "SCB.BK", name: "SCB X (เอสซีบี เอกซ์ / ไทยพาณิชย์ / SCB)", type: "EQUITY", exchange: "SET" },
  { symbol: "SCC.BK", name: "Siam Cement Group (ปูนซิเมนต์ไทย / SCC / ปูนใหญ่)", type: "EQUITY", exchange: "SET" },
  { symbol: "SCCC.BK", name: "Siam City Cement (ปูนซีเมนต์นครหลวง / SCCC / ปูนกลาง)", type: "EQUITY", exchange: "SET" },
  { symbol: "SCGP.BK", name: "SCG Packaging (เอสซีจี แพคเกจจิ้ง / SCGP)", type: "EQUITY", exchange: "SET" },
  { symbol: "SINGER.BK", name: "Singer Thailand (ซิงเกอร์ประเทศไทย / SINGER)", type: "EQUITY", exchange: "SET" },
  { symbol: "SIRI.BK", name: "Sansiri (แสนสิริ / SIRI)", type: "EQUITY", exchange: "SET" },
  { symbol: "SIS.BK", name: "SIS Distribution (ซิส ดิสทริบิวชั่น / SIS)", type: "EQUITY", exchange: "SET" },
  { symbol: "SPALI.BK", name: "Supalai (ศุภาลัย / SPALI)", type: "EQUITY", exchange: "SET" },
  { symbol: "SPCG.BK", name: "SPCG (เอสพีซีจี / SPCG)", type: "EQUITY", exchange: "SET" },
  { symbol: "SPRC.BK", name: "Star Petroleum Refining (สตาร์ ปิโตรเลียม รีไฟนนิ่ง / SPRC)", type: "EQUITY", exchange: "SET" },
  { symbol: "STA.BK", name: "Sri Trang Agro-Industry (ศรีตรังแอโกรอินดัสทรี / STA)", type: "EQUITY", exchange: "SET" },
  { symbol: "STEC.BK", name: "Sino-Thai Engineering (ซิโน-ไทย เอ็นจีเนียริ่ง / STEC)", type: "EQUITY", exchange: "SET" },
  { symbol: "SUPER.BK", name: "Super Energy Corporation (ซุปเปอร์ เอนเนอร์ยี คอร์เปอเรชัน / SUPER)", type: "EQUITY", exchange: "SET" },
  { symbol: "SVI.BK", name: "SVI (เอสวีไอ / SVI)", type: "EQUITY", exchange: "SET" },
  { symbol: "TASCO.BK", name: "Tipco Asphalt (ทิปโก้แอสฟัลท์ / TASCO)", type: "EQUITY", exchange: "SET" },
  { symbol: "TCAP.BK", name: "Thanachart Capital (ทุนธนชาต / TCAP)", type: "EQUITY", exchange: "SET" },
  { symbol: "THAI.BK", name: "Thai Airways (การบินไทย / THAI)", type: "EQUITY", exchange: "SET" },
  { symbol: "THANI.BK", name: "Ratchthani Leasing (ราชธานีลิสซิ่ง / THANI)", type: "EQUITY", exchange: "SET" },
  { symbol: "THCOM.BK", name: "Thaicom (ไทยคม / THCOM)", type: "EQUITY", exchange: "SET" },
  { symbol: "THG.BK", name: "Thonburi Healthcare Group (ธนบุรี เฮลท์แคร์ กรุ๊ป / THG)", type: "EQUITY", exchange: "SET" },
  { symbol: "TIDLOR.BK", name: "Ngern Tid Lor (เงินติดล้อ / TIDLOR)", type: "EQUITY", exchange: "SET" },
  { symbol: "TIPH.BK", name: "Dhipaya Group Holdings (ทิพย กรุ๊ป โฮลดิ้งส์ / TIPH)", type: "EQUITY", exchange: "SET" },
  { symbol: "TISCO.BK", name: "Tisco Financial Group (ทิสโก้ไฟแนนเชียลกรุ๊ป / TISCO)", type: "EQUITY", exchange: "SET" },
  { symbol: "TKN.BK", name: "Taokaenoi Food & Marketing (เถ้าแก่น้อย / TKN)", type: "EQUITY", exchange: "SET" },
  { symbol: "TOA.BK", name: "TOA Paint (ทีโอเอ เพ้นท์ / TOA)", type: "EQUITY", exchange: "SET" },
  { symbol: "TOP.BK", name: "Thai Oil (ไทยออยล์ / TOP)", type: "EQUITY", exchange: "SET" },
  { symbol: "TPIPL.BK", name: "TPI Polene (ทีพีไอ โพลีน / TPIPL)", type: "EQUITY", exchange: "SET" },
  { symbol: "TPIPP.BK", name: "TPI Polene Power (ทีพีไอ โพลีน เพาเวอร์ / TPIPP)", type: "EQUITY", exchange: "SET" },
  { symbol: "TQM.BK", name: "TQM Alpha (ทีคิวเอ็ม อัลฟา / TQM)", type: "EQUITY", exchange: "SET" },
  { symbol: "TRUE.BK", name: "True Corporation (ทรู คอร์ปอเรชัน / TRUE)", type: "EQUITY", exchange: "SET" },
  { symbol: "TTA.BK", name: "Thoresen Thai Agencies (โทรีเซนไทย เอเยนต์ซีส์ / TTA)", type: "EQUITY", exchange: "SET" },
  { symbol: "TTB.BK", name: "TMBThanachart Bank (ธนาคารทหารไทยธนชาต / TTB / ทีทีบี)", type: "EQUITY", exchange: "SET" },
  { symbol: "TTW.BK", name: "TTW (ทีทีดับบลิว / TTW)", type: "EQUITY", exchange: "SET" },
  { symbol: "TU.BK", name: "Thai Union Group (ไทยยูเนียน กรุ๊ป / TU)", type: "EQUITY", exchange: "SET" },
  { symbol: "VGI.BK", name: "VGI (วีจีไอ / VGI)", type: "EQUITY", exchange: "SET" },
  { symbol: "WHA.BK", name: "WHA Corporation (ดับบลิวเอชเอ คอร์ปอเรชัน / WHA)", type: "EQUITY", exchange: "SET" },
  { symbol: "WHAUP.BK", name: "WHA Utilities and Power (ดับบลิวเอชเอ ยูทิลิตี้ส์ แอนด์ พาวเวอร์ / WHAUP)", type: "EQUITY", exchange: "SET" }
];
