/**
 * constants.js
 * Static data constants shared across the application.
 * Pure data — no logic, no imports.
 *
 * Contents:
 *   - CATEGORY_LABELS   — asset category display names (Thai)
 *   - PRESET_AVATARS    — built-in profile avatar options
 *   - CURRENCIES        — 165+ world currencies for fiat asset selection
 */

/* ─── Asset Categories ─── */
export const CATEGORY_LABELS = {
  stock:  "หุ้น",
  option: "ออปชัน",
  crypto: "คริปโต",
  gold:   "ทองคำ/น้ำมัน",
  fiat:   "เงินสด",
};

/* ─── Preset Profile Avatars ─── */
export const PRESET_AVATARS = [
  {
    id: "bull",
    emoji: "📈",
    bg: "linear-gradient(135deg, #3B82F6 0%, #10B981 100%)",
    svg: `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" width="100" height="100"><defs><linearGradient id="bull-g" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="%233B82F6"/><stop offset="100%" stop-color="%2310B981"/></linearGradient></defs><rect width="100" height="100" rx="50" fill="url(%23bull-g)"/><text x="50%" y="65%" font-size="50" text-anchor="middle" font-family="sans-serif">📈</text></svg>`
  },
  {
    id: "bear",
    emoji: "🐻",
    bg: "linear-gradient(135deg, #8B5CF6 0%, #EF4444 100%)",
    svg: `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" width="100" height="100"><defs><linearGradient id="bear-g" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="%238B5CF6"/><stop offset="100%" stop-color="%23EF4444"/></linearGradient></defs><rect width="100" height="100" rx="50" fill="url(%23bear-g)"/><text x="50%" y="68%" font-size="50" text-anchor="middle" font-family="sans-serif">🐻</text></svg>`
  },
  {
    id: "lion",
    emoji: "🦁",
    bg: "linear-gradient(135deg, #F59E0B 0%, #EF4444 100%)",
    svg: `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" width="100" height="100"><defs><linearGradient id="lion-g" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="%23F59E0B"/><stop offset="100%" stop-color="%23EF4444"/></linearGradient></defs><rect width="100" height="100" rx="50" fill="url(%23lion-g)"/><text x="50%" y="68%" font-size="50" text-anchor="middle" font-family="sans-serif">🦁</text></svg>`
  },
  {
    id: "koala",
    emoji: "🐨",
    bg: "linear-gradient(135deg, #0D9488 0%, #06B6D4 100%)",
    svg: `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" width="100" height="100"><defs><linearGradient id="koala-g" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="%230D9488"/><stop offset="100%" stop-color="%2306B6D4"/></linearGradient></defs><rect width="100" height="100" rx="50" fill="url(%23koala-g)"/><text x="50%" y="68%" font-size="50" text-anchor="middle" font-family="sans-serif">🐨</text></svg>`
  },
  {
    id: "unicorn",
    emoji: "🦄",
    bg: "linear-gradient(135deg, #6366F1 0%, #EC4899 100%)",
    svg: `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" width="100" height="100"><defs><linearGradient id="uni-g" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="%236366F1"/><stop offset="100%" stop-color="%23EC4899"/></linearGradient></defs><rect width="100" height="100" rx="50" fill="url(%23uni-g)"/><text x="50%" y="68%" font-size="50" text-anchor="middle" font-family="sans-serif">🦄</text></svg>`
  },
  {
    id: "fox",
    emoji: "🦊",
    bg: "linear-gradient(135deg, #8B5CF6 0%, #D946EF 100%)",
    svg: `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" width="100" height="100"><defs><linearGradient id="fox-g" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="%238B5CF6"/><stop offset="100%" stop-color="%23D946EF"/></linearGradient></defs><rect width="100" height="100" rx="50" fill="url(%23fox-g)"/><text x="50%" y="68%" font-size="50" text-anchor="middle" font-family="sans-serif">🦊</text></svg>`
  },
];

/* ─── Global Currencies List (165+ สกุลเงินทั่วโลก) ─── */
export const CURRENCIES = [
  { code: "THB", name: "Thai Baht (บาท 🇹🇭)" },
  { code: "USD", name: "US Dollar (ดอลลาร์สหรัฐ 🇺🇸)" },
  { code: "EUR", name: "Euro (ยูโร 🇪🇺)" },
  { code: "GBP", name: "British Pound (ปอนด์สหราชอาณาจักร 🇬🇧)" },
  { code: "JPY", name: "Japanese Yen (เยนญี่ปุ่น 🇯🇵)" },
  { code: "SGD", name: "Singapore Dollar (ดอลลาร์สิงคโปร์ 🇸🇬)" },
  { code: "HKD", name: "Hong Kong Dollar (ดอลลาร์ฮ่องกง 🇭🇰)" },
  { code: "AUD", name: "Australian Dollar (ดอลลาร์ออสเตรเลีย 🇦🇺)" },
  { code: "CAD", name: "Canadian Dollar (ดอลลาร์แคนาดา 🇨🇦)" },
  { code: "CHF", name: "Swiss Franc (ฟรังก์สวิส 🇨🇭)" },
  { code: "CNY", name: "Chinese Yuan (หยวนจีน 🇨🇳)" },
  { code: "KRW", name: "South Korean Won (วอนเกาหลีใต้ 🇰🇷)" },
  { code: "TWD", name: "New Taiwan Dollar (ดอลลาร์ไต้หวัน 🇹🇼)" },
  { code: "INR", name: "Indian Rupee (รูปีอินเดีย 🇮🇳)" },
  { code: "NZD", name: "New Zealand Dollar (ดอลลาร์นิวซีแลนด์ 🇳🇿)" },
  { code: "MYR", name: "Malaysian Ringgit (ริงกิตมาเลเซีย 🇲🇾)" },
  { code: "IDR", name: "Indonesian Rupiah (รูเปียห์อินโดนีเซีย 🇮🇩)" },
  { code: "PHP", name: "Philippine Peso (เปโซฟิลิปปินส์ 🇵🇭)" },
  { code: "VND", name: "Vietnamese Dong (ดองเวียดนาม 🇻🇳)" },
  { code: "DKK", name: "Danish Krone (โครนเดนมาร์ก 🇩🇰)" },
  { code: "NOK", name: "Norwegian Krone (โครนนอร์เวย์ 🇳🇴)" },
  { code: "SEK", name: "Swedish Krona (โครนสวีเดน 🇸🇪)" },
  { code: "AED", name: "UAE Dirham (ดีแรฮมสหรัฐอาหรับเอมิเรตส์ 🇦🇪)" },
  { code: "SAR", name: "Saudi Riyal (ริยัลซาอุดีอาระเบีย 🇸🇦)" },
  { code: "RUB", name: "Russian Ruble (รูเบิลรัสเซีย 🇷🇺)" },
  { code: "TRY", name: "Turkish Lira (ลีราตุรกี 🇹🇷)" },
  { code: "BRL", name: "Brazilian Real (เรียลบราซิล 🇧🇷)" },
  { code: "MXN", name: "Mexican Peso (เปโซเม็กซิโก 🇲🇽)" },
  { code: "ZAR", name: "South African Rand (แรนด์แอฟริกาใต้ 🇿🇦)" },
  { code: "AFN", name: "Afghan Afghani (อัฟกานิอัฟกานิสถาน 🇦🇫)" },
  { code: "ALL", name: "Albanian Lek (เลกแอลเบเนีย 🇦🇱)" },
  { code: "AMD", name: "Armenian Dram (ดรัมอาร์เมเนีย 🇦🇲)" },
  { code: "ANG", name: "Netherlands Antillean Guilder (กิลเดอร์เนเธอร์แลนด์แอนทิลลิส 🇨🇼)" },
  { code: "AOA", name: "Angolan Kwanza (ควานซาแองโกลา 🇦🇴)" },
  { code: "ARS", name: "Argentine Peso (เปโซอาร์เจนตินา 🇦🇷)" },
  { code: "AWG", name: "Aruban Florin (ฟลอรินอารูบา 🇦🇼)" },
  { code: "AZN", name: "Azerbaijani Manat (มานัตอาเซอร์ไบจาน 🇦🇿)" },
  { code: "BAM", name: "Bosnia convertible mark (มาร์กบอสเนีย 🇧🇦)" },
  { code: "BBD", name: "Barbadian Dollar (ดอลลาร์บาร์เบโดส 🇧🇧)" },
  { code: "BDT", name: "Bangladeshi Taka (ตากาบังกลาเทศ 🇧🇩)" },
  { code: "BGN", name: "Bulgarian Lev (เลฟบัลแกเรีย 🇧🇬)" },
  { code: "BHD", name: "Bahraini Dinar (ดีนาร์บาห์เรน 🇧🇭)" },
  { code: "BIF", name: "Burundian Franc (ฟรังก์บุรุนดี 🇧🇮)" },
  { code: "BMD", name: "Bermudian Dollar (ดอลลาร์เบอร์มิวดา 🇧🇲)" },
  { code: "BND", name: "Brunei Dollar (ดอลลาร์บรูไน 🇧🇳)" },
  { code: "BOB", name: "Bolivian Boliviano (โบลีเวียโน 🇧🇴)" },
  { code: "BSD", name: "Bahamian Dollar (ดอลลาร์บาฮามาส 🇧🇸)" },
  { code: "BTN", name: "Bhutanese Ngultrum (เอ็นกุลตรัม 🇧🇹)" },
  { code: "BWP", name: "Botswana Pula (ปูลาบอตสวานา 🇧🇼)" },
  { code: "BYN", name: "Belarusian Ruble (รูเบิลเบลารุส 🇧🇾)" },
  { code: "BZD", name: "Belize Dollar (ดอลลาร์เบลีซ 🇧🇿)" },
  { code: "CDF", name: "Congolese Franc (ฟรังก์คองโก 🇨🇩)" },
  { code: "CLP", name: "Chilean Peso (เปโซชิลี 🇨🇱)" },
  { code: "COP", name: "Colombian Peso (เปโซโคลอมเบีย 🇨🇴)" },
  { code: "CRC", name: "Costa Rican Colón (โกลอนคอสตาริกา 🇨🇷)" },
  { code: "CUP", name: "Cuban Peso (เปโซคิวบา 🇨🇺)" },
  { code: "CVE", name: "Cape Verdean Escudo (เอสคูโดเคปเวิร์ด 🇨🇻)" },
  { code: "CZK", name: "Czech Koruna (โครูนาเช็ก 🇨🇿)" },
  { code: "DJF", name: "Djiboutian Franc (ฟรังก์จิบูตี 🇩🇯)" },
  { code: "DOP", name: "Dominican Peso (เปโซโดมินิกัน 🇩🇴)" },
  { code: "DZD", name: "Algerian Dinar (ดีนาร์แอลจีเรีย 🇩🇿)" },
  { code: "EGP", name: "Egyptian Pound (ปอนด์อียิปต์ 🇪🇬)" },
  { code: "ERN", name: "Eritrean Nakfa (แนกฟา 🇪🇷)" },
  { code: "ETB", name: "Ethiopian Birr (เบอร์เอธิโอเปีย 🇪🇹)" },
  { code: "FJD", name: "Fijian Dollar (ดอลลาร์ฟิจิ 🇫🇯)" },
  { code: "FKP", name: "Falkland Islands Pound (ปอนด์หมู่เกาะฟอล์กแลนด์ 🇫🇰)" },
  { code: "FOK", name: "Faroese Króna (โครนาหมู่เกาะแฟโร 🇫🇴)" },
  { code: "GEL", name: "Georgian Lari (ลารีจอร์เจีย 🇬🇪)" },
  { code: "GGP", name: "Guernsey Pound (ปอนด์เกิร์นซีย์ 🇬🇬)" },
  { code: "GHS", name: "Ghanaian Cedi (เซดีกานา 🇬🇭)" },
  { code: "GIP", name: "Gibraltar Pound (ปอนด์ยิบรอลตาร์ 🇬🇮)" },
  { code: "GMD", name: "Gambian Dalasi (ดาลาซีกัมเบีย 🇬🇲)" },
  { code: "GNF", name: "Guinean Franc (ฟรังก์กินี 🇬🇳)" },
  { code: "GTQ", name: "Guatemalan Quetzal (เกตซัล 🇬🇹)" },
  { code: "GYD", name: "Guyanese Dollar (ดอลลาร์กายอานา 🇬🇾)" },
  { code: "HNL", name: "Honduran Lempira (เลมปีราฮอนดูรัส 🇭🇳)" },
  { code: "HRK", name: "Croatian Kuna (คูนาโครเอเชีย 🇭🇷)" },
  { code: "HTG", name: "Haitian Gourde (กูร์ดเฮติ 🇭🇹)" },
  { code: "HUF", name: "Hungarian Forint (ฟอรินต์ฮังการี 🇭🇺)" },
  { code: "ILS", name: "Israeli New Shekel (เชเกลอิสราเอล 🇮🇱)" },
  { code: "IMP", name: "Isle of Man Pound (ปอนด์เกาะแมน 🇮🇲)" },
  { code: "IQD", name: "Iraqi Dinar (ดีนาร์อิรัก 🇮🇶)" },
  { code: "IRR", name: "Iranian Rial (เรียลอิหร่าน 🇮🇷)" },
  { code: "ISK", name: "Icelandic Króna (โครนาไอซ์แลนด์ 🇮🇸)" },
  { code: "JEP", name: "Jersey Pound (ปอนด์เจอร์ซีย์ 🇯🇪)" },
  { code: "JMD", name: "Jamaican Dollar (ดอลลาร์จาเมกา 🇯🇲)" },
  { code: "JOD", name: "Jordanian Dinar (ดีนาร์จอร์แดน 🇯🇴)" },
  { code: "KES", name: "Kenyan Shilling (ชิลลิงเคนยา 🇰🇪)" },
  { code: "KGS", name: "Kyrgyzstani Som (ซอมคีร์กีซสถาน 🇰🇬)" },
  { code: "KHR", name: "Cambodian Riel (เรียลกัมพูชา 🇰🇭)" },
  { code: "KID", name: "Kiribati Dollar (ดอลลาร์คิริบาส 🇰🇮)" },
  { code: "KMF", name: "Comorian Franc (ฟรังก์คอโมโรส 🇰🇲)" },
  { code: "KPW", name: "North Korean Won (วอนเกาหลีเหนือ 🇰🇵)" },
  { code: "KWD", name: "Kuwaiti Dinar (ดีนาร์คูเวต 🇰🇼)" },
  { code: "KYD", name: "Cayman Islands Dollar (ดอลลาร์หมู่เกาะเคย์แมน 🇰🇾)" },
  { code: "KZT", name: "Kazakhstani Tenge (เทงเกคาซัคสถาน 🇰🇿)" },
  { code: "LAK", name: "Lao Kip (กีบลาว 🇱🇦)" },
  { code: "LBP", name: "Lebanese Pound (ปอนด์เลบานอน 🇱🇧)" },
  { code: "LKR", name: "Sri Lankan Rupee (รูปีศรีลังกา 🇱🇰)" },
  { code: "LRD", name: "Liberian Dollar (ดอลลาร์ไลบีเรีย 🇱🇷)" },
  { code: "LSL", name: "Lesotho Loti (โลตีเลโซโท 🇱🇸)" },
  { code: "LYD", name: "Libyan Dinar (ดีนาร์ลิเบีย 🇱🇾)" },
  { code: "MAD", name: "Moroccan Dirham (ดีแรฮมโมร็อกโก 🇲🇦)" },
  { code: "MDL", name: "Moldovan Leu (เลวมอลโดวา 🇲🇩)" },
  { code: "MGA", name: "Malagasy Ariary (อาเรียรี 🇲🇬)" },
  { code: "MKD", name: "Macedonian Denar (ดีนาร์มาซิโดเนีย 🇲🇰)" },
  { code: "MMK", name: "Myanmar Kyat (จ๊าดพม่า 🇲🇲)" },
  { code: "MNT", name: "Mongolian Tögrög (ทูกริกมองโกเลีย 🇲🇳)" },
  { code: "MOP", name: "Macanese Pataca (ปาตากามาเก๊า 🇲🇴)" },
  { code: "MRU", name: "Mauritanian Ouguiya (อูกียา 🇲🇷)" },
  { code: "MUR", name: "Mauritian Rupee (รูปีมอริเชียส 🇲🇺)" },
  { code: "MVR", name: "Maldivian Rufiyaa (รูฟิยาห์ 🇲🇻)" },
  { code: "MWK", name: "Malawian Kwacha (ควาชา 🇲🇼)" },
  { code: "MZN", name: "Mozambican Metical (เมทิคัล 🇲🇿)" },
  { code: "NAD", name: "Namibian Dollar (ดอลลาร์นามิเบีย 🇳🇦)" },
  { code: "NGN", name: "Nigerian Naira (ไนราไนจีเรีย 🇳🇬)" },
  { code: "NIO", name: "Nicaraguan Córdoba (กอร์โดบา 🇳🇮)" },
  { code: "NPR", name: "Nepalese Rupee (รูปีเนปาล 🇳🇵)" },
  { code: "OMR", name: "Omani Rial (เรียลโอมาน 🇴🇲)" },
  { code: "PAB", name: "Panamanian Balboa (บัลบัว 🇵🇦)" },
  { code: "PEN", name: "Peruvian Sol (ซอลเปรู 🇵🇪)" },
  { code: "PGK", name: "Papua New Guinean Kina (กีนา 🇵🇬)" },
  { code: "PKR", name: "Pakistani Rupee (รูปีปากีสถาน 🇵🇰)" },
  { code: "PLN", name: "Polish Złoty (ซวอตี 🇵🇱)" },
  { code: "PYG", name: "Paraguayan Guaraní (กวารานี 🇵🇾)" },
  { code: "QAR", name: "Qatari Riyal (ริยัลกาตาร์ 🇶🇦)" },
  { code: "RON", name: "Romanian Leu (เลวโรมาเนีย 🇷🇴)" },
  { code: "RSD", name: "Serbian Dinar (ดีนาร์เซอร์เบีย 🇷🇸)" },
  { code: "RWF", name: "Rwandan Franc (ฟรังก์รวันดา 🇷🇼)" },
  { code: "SBD", name: "Solomon Islands Dollar (ดอลลาร์หมู่เกาะโซโลมอน 🇸🇧)" },
  { code: "SCR", name: "Seychellois Rupee (รูปีเซเชลส์ 🇸🇨)" },
  { code: "SDG", name: "Sudanese Pound (ปอนด์ซูดาน 🇸🇩)" },
  { code: "SHP", name: "Saint Helena Pound (ปอนด์เซนต์เฮเลนา 🇸🇭)" },
  { code: "SLE", name: "Sierra Leonean Leone (ลีโอน 🇸🇱)" },
  { code: "SOS", name: "Somali Shilling (ชิลลิงโซมาเลีย 🇸🇴)" },
  { code: "SRD", name: "Surinamese Dollar (ดอลลาร์สุรินทร์ 🇸🇷)" },
  { code: "SSP", name: "South Sudanese Pound (ปอนด์ซูดานใต้ 🇸🇸)" },
  { code: "STN", name: "São Tomé Dobra (โดบรา 🇸🇹)" },
  { code: "SVC", name: "Salvadoran Colón (โกลอน 🇸🇻)" },
  { code: "SYP", name: "Syrian Pound (ปอนด์ซีเรีย 🇸🇾)" },
  { code: "SZL", name: "Swazi Lilangeni (ลีลันเกนี 🇸🇿)" },
  { code: "TJS", name: "Tajikistani Somoni (โซโมนิ 🇹🇯)" },
  { code: "TMT", name: "Turkmenistan Manat (มานัต 🇹🇲)" },
  { code: "TND", name: "Tunisian Dinar (ดีนาร์ตูนิเซีย 🇹🇳)" },
  { code: "TOP", name: "Tongan Paʻanga (พาแองกา 🇹🇴)" },
  { code: "TTD", name: "Trinidad Dollar (ดอลลาร์ตรินิแดด 🇹🇹)" },
  { code: "TVD", name: "Tuvaluan Dollar (ดอลลาร์ตูวาลู 🇹🇻)" },
  { code: "TZS", name: "Tanzanian Shilling (ชิลลิงแทนซาเนีย 🇹🇿)" },
  { code: "UAH", name: "Ukrainian Hryvnia (ฮริฟเนียยูเครน 🇺🇦)" },
  { code: "UGX", name: "Ugandan Shilling (ชิลลิงยูแกนดา 🇺🇬)" },
  { code: "UYU", name: "Uruguayan Peso (เปโซอุรุกวัย 🇺🇾)" },
  { code: "UZS", name: "Uzbekistani Som (ซอมอุซเบกิสถาน 🇺🇿)" },
  { code: "VES", name: "Venezuelan Bolívar (โบลิวาร์ 🇻🇪)" },
  { code: "VUV", name: "Vanuatu Vatu (วาตู 🇻🇺)" },
  { code: "WST", name: "Samoan Tālā (ทาลา 🇼🇸)" },
  { code: "XAF", name: "Central African CFA Franc (ฟรังก์แอฟริกากลาง 🇨🇫)" },
  { code: "XCD", name: "East Caribbean Dollar (ดอลลาร์แคริบเบียนตะวันออก 🇩🇲)" },
  { code: "XOF", name: "West African CFA Franc (ฟรังก์แอฟริกาตะวันตก 🇸🇳)" },
  { code: "XPF", name: "CFP Franc (ฟรังก์ซีเอฟพี 🇵🇫)" },
  { code: "YER", name: "Yemeni Rial (เรียลเยเมน 🇾🇪)" },
  { code: "ZMW", name: "Zambian Kwacha (ควาชาแซมเบีย 🇿🇲)" },
  { code: "ZWL", name: "Zimbabwean Dollar (ดอลลาร์ซิมบับเว 🇿🇼)" },
];
